### ISSUE TITLE
mfw

### ISSUE THREAD

**Issue by DNDEBUG** [zeta3301/shell4chan#1]
>can't see loli because tty only supports up to 512 glyphs (half of it if i want colors)
![c61](https://github.com/zeta3301/shell4chan/assets/98880063/b625e833-0030-4e14-91ef-457a5205bb64)

**Comment by zeta3301** [comment]
sorry tty chad.You can replace image_preview with this image_display="$(jp2a --size=$(($picrel_width / 10))x$(($picrel_height / 10)) ~/.cache/shell4chan/"$picrel")"

**Comment by DNDEBUG** [comment]
it ok, i fixed it
emailing you the fix right now

**Comment by zeta3301** [comment]
you can maake pull request.

**Comment by G2G2G2G** [comment]
just install more bloat so you get more pixels, stupidass

**Comment by DNDEBUG** [comment]
>Just install more bloat
ok spook
literal fed here telling me to install alexa

**Comment by G2G2G2G** [comment]
install x11 AND wayland AND proprietary novidya drivers

**Comment by DNDEBUG** [comment]
i'd rater install Haiku
